<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
        <LangVersion>8</LangVersion>
        <Nullable>disable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <Authors>ParaParty</Authors>
        <Product>ParaParty Util Colors</Product>
        <PackageProjectUrl>https://pkg.para.party/ParaPartyUtil</PackageProjectUrl>
        <RepositoryUrl>https://github.com/ParaParty/ParaPartyUtil/</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Description>ParaParty Util Colors</Description>

        <RootNamespace>Paraparty</RootNamespace>
        <AssemblyName>Paraparty.Colors</AssemblyName>

        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageId>Paraparty.Colors</PackageId>
        <Version>3.1.0</Version>
        <AssemblyVersion>3.1.0.0</AssemblyVersion>
        <FileVersion>3.1.0.0</FileVersion>

        <DefineConstants Condition="'$(TargetFramework)' == 'netstandard2.0'">NET_STANDARD_2_0</DefineConstants>
        <DefineConstants Condition="'$(TargetFramework)' == 'netstandard2.1'">NET_STANDARD_2_1</DefineConstants>

    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Condition="'$(TargetFramework)' == 'netstandard2.0'" Include="..\UnityPolyfill\UnityPolyfill.csproj" />
    </ItemGroup>

</Project>
