<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard1.2;netstandard2.0;net5.0;</TargetFrameworks>
        <LangVersion>7.2</LangVersion>
        <Nullable>disable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <Authors>ParaParty</Authors>
        <Product>ParaParty Util JsonChan</Product>
        <PackageProjectUrl>https://pkg.para.party/ParaPartyUtil</PackageProjectUrl>
        <RepositoryUrl>https://github.com/ParaParty/ParaPartyUtil/</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Description>ParaParty Util JsonChan</Description>

        <RootNamespace>Paraparty</RootNamespace>
        <AssemblyName>Paraparty.JsonChan</AssemblyName>

        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageId>Paraparty.JsonChan</PackageId>
        <Version>3.1.0</Version>
        <AssemblyVersion>3.1.0.0</AssemblyVersion>
        <FileVersion>3.1.0.0</FileVersion>
    </PropertyGroup>

    <ItemGroup Condition="$(TargetFramework.StartsWith('netstandard'))">
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0"/>
    </ItemGroup>
</Project>
